jbake-org/jbake.org

content/community/sites.ad
Added my JBake powered site to the list.
=> Updated sites.ad with Teh Artikli blog

content/community/sites.ad
I added my blog to the sites list
=> added http://grycman.eu to sites.ad

content/community/sites.ad
Adding Víctor Orozco's blog to sites using jbake
=> Proposing a new website

content/community/sites.ad
We use JBake and love it! Our internal documentation is generated by scripts and plugged into a JBake workflow.
=> Added site using JBake

content/community/sites.ad
Added my blog which is baked with JBake.
=> Added site baked with JBake

content/docs/2.4.0/installation.ad
Updated links and labels for GVM (now SDKMAN)
=> [#44] update docs - GVM to SDKMAN change

templates/news.ftl
* Add paragraph per news item.
=> Upgrade to international date format

content/community/sites.ad
New blog using JBake, [http://luisgc.github.io/blog/](http://luisgc.github.io/blog/)
=> LuisGC's blog added

templates/footer.ftl
In case, Gitter Chat room should be shown on jbake.org.
=> Added Gitter Chat for JBake

content/docs/2.5.1/configuration.ad
Probably documents is the best location for these instructions. Take a look at this and merge if good.
=> Updated instructions to enable asciidoctor admonition icons

content/docs/2.6.0/project-structure.ad
This PR Updates docs for JBake 2.6.0 jbake-org/jbake.org#79.
=> Update docs for jbake-org/jbake#390

content/docs/2.6.0/usage.ad
This PR updates JBake 2.6.0 Docs per jbake-org/jbake.org#79.
=> Update docs for jbake-org/jbake#384

content/docs/2.6.0/data-variables.ad
Completes one task for jbake-org/jbake.org#79.
=> Updated docs for jbake-org/jbake#371

content/docs/2.6.0/content-files.ad
Updates documentation for #79 . Updates document for jbake-org/jbake#367.
=> Updated doc for Jbake-org/jbake#367

content/docs/2.6.0/build-tool-integration.ad
=> fix gradle links

content/docs/latest/usage.adoc
docs for the PR at https://github.com/jbake-org/jbake/pull/564
=> add docs for log and lib setup

content/docs/2.6.4/build-tool-integration.adoc, content/docs/latest/build-tool-integration.adoc
=> Updated pages to reflect new release of Maven plugin.

content/docs/2.6.5/build-tool-integration.adoc, content/docs/2.6.5/configuration.adoc, content/docs/2.6.5/content-files.adoc, content/docs/2.6.5/data-variables.adoc, content/docs/2.6.5/index.adoc, content/docs/2.6.5/installation.adoc, content/docs/2.6.5/overview.adoc, content/docs/2.6.5/project-structure.adoc, content/docs/2.6.5/quickstart-guide.adoc, content/docs/2.6.5/template.adoc, content/docs/2.6.5/usage.adoc, content/docs/2.6.5/use-as-library.adoc, content/docs/index.adoc, content/docs/latest/build-tool-integration.adoc, content/docs/latest/content-files.adoc, content/docs/latest/data-variables.adoc, content/download.adoc, content/news/jbake-v2-6-5-released.adoc, templates/index.ftl
Preparation for upcoming release 2.6.5
=> Release 2.6.5

content/docs/2.6.5/index.adoc, content/docs/latest/configuration.adoc, content/docs/latest/index.adoc, content/docs/latest/installation.adoc, content/docs/latest/project-structure.adoc, content/docs/latest/quickstart-guide.adoc, content/docs/latest/use-as-library.adoc, templates/index.ftl
Plus some small improvements and corrections.
=> Update docs for 2.6.6

content/community/freenode.adoc, content/community/index.adoc, templates/index.ftl
Removed Freenode page and any links to Freenode.
Replaced badge for Ohloh with Appveyor.
Updated link for Travis.
=> Cleanup of links and chat references.

content/community/sites.adoc
=> adding Eudris Cabrera's Personal site

README.md
=> Update link  to use TLS
